Upgrade to Flutter 1.22
WorldHealthOrganization/app pull request #1557
Opened 2020-10-05 23:15 UTC by theswerd

### Upgrade to Flutter 1.22

- Upgraded to Flutter 1.22
- Replaced all **flatButtons** with their replacement **textButtons**
- Incorporated **Padding** in **PageButtons** into the button styling
- Started Restyling code to new Flutter standards -- still more to do

##### Screenshots:
###### Old:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-05 at 14 43 25](https://user-images.githubusercontent.com/38309438/95140610-28396800-0724-11eb-9cfb-9fc7fcd39caa.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-05 at 14 43 02](https://user-images.githubusercontent.com/38309438/95140613-28d1fe80-0724-11eb-898a-7a84bd5992aa.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-05 at 14 38 25](https://user-images.githubusercontent.com/38309438/95140615-296a9500-0724-11eb-9ba7-b3d4508d0a8f.png)
###### New:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-05 at 16 07 54](https://user-images.githubusercontent.com/38309438/95141003-f543a400-0724-11eb-8334-477a1fa71da7.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-05 at 16 07 46](https://user-images.githubusercontent.com/38309438/95141004-f5dc3a80-0724-11eb-938a-94f003f75aab.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-05 at 16 07 30](https://user-images.githubusercontent.com/38309438/95141005-f674d100-0724-11eb-9654-81e1e3a2ba42.png)

#### How did you test the change?
* [x] iOS Simulator
* [ ] Android Emulator
* [ ] iOS Device
* [ ] Android Device
* [ ] `curl` to a dev App Engine server

---

#### Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).

- [ ] REQUIRED: Do you have an Issue **assigned to you** for this PR?
- [x] Provided detailed pull request description and a succinct title
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [docs/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/docs/credits.yaml) file (if you want it to be).

2020-10-06 04:02 UTC, brunobowden requested changes
@theswerd - this is a welcome improvement. Couple of overall thoughts:

Need a Flutter expert to look at this which isn't me. Maybe @britannio or pinging on the #flutter channel on Slack would work for this.

`-nullsafety` is using prerelease libraries. This should be split out to another commit and a separate discussion. At this point, I don't think that the libraries are meant for public discussion and it's not worth the risk. It's a big decision to use prerelease libraries, so it's essential that important like that should be in the commit description! Given this fix, I thought you wouldn't see this as a suggestion:
https://github.com/dart-lang/sdk/issues/42657

Screenshots should include the main page as that's the most important one. I've scoped your screenshots in <details>...</details> as otherwise the layout becomes unmanageable in GitHub.

If you think that a series of improvements is need for Flutter 1.22. Please create issues for them. Maybe even a combined issue with several items listed out. It's important to do modest incremental changes, so that if there's an issue, we can better bisect to find the cause.

2020-10-06 11:33 UTC, britannio commented on client/flutter/pubspec.lock
> +  dart: ">=2.10.0-110 <2.11.0"
I don't think this is an issue.

2020-10-06 16:16 UTC, theswerd commented on client/flutter/lib/components/dialogs.dart
> +              child: Text(
I believe that TODO is outdated, as there are no hard coded strings in this file

2020-10-06 16:16 UTC, theswerd commented on client/flutter/lib/components/page_button.dart
> +      // color: widget.backgroundColor,
Ah Yep -- Will delete that today

2020-10-07 07:12 UTC, brunobowden commented
Need resolution on Flutter 1.22.0 `-nullsafety` dependencies: https://github.com/flutter/flutter/issues/67473

2020-10-08 21:42 UTC, yukuairoy approved these changes

2020-10-10 02:49 UTC, brunobowden commented
@theswerd - time to rebase on master and see what's left of the commit. I still think there's some worthwhile changes in here.

2020-10-10 20:26 UTC, closed without merging