Country selector search option #1705
WorldHealthOrganization/app pull request #1817
Opened 2020-12-09 17:32 UTC by Henrymarks1

## Screenshots

<details>
<summary>Screenshots</summary>

<img src="https://user-images.githubusercontent.com/58492005/101664361-9b9b7680-3a00-11eb-85a8-13a574b542e2.png" height="300">

![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-09 at 09 22 20](https://user-images.githubusercontent.com/58492005/101664374-9e966700-3a00-11eb-98bb-e8ac4f780ef5.png)

</details>

## How did you test the change?

- [x] iOS Simulator
- [x] iOS Device
- [ ] Android Simulator
- [ ] Android Device
- [ ] `curl` to a dev App Engine server
- [ ] other, please describe

## Checklist:

- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md) and verified that all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE).

2020-12-13 23:07 UTC, brunobowden requested changes
@Henrymarks1 - thanks for your help on this. It's a definite improvement. I'd normally advise against this but since the initial launch will soon happen in Nigeria, can you hard code Nigeria to appear at the top of the list.

We'll naturally need to fix this before rolling out in other countries. I'm tracking that and some other improvements on this issue:
https://github.com/WorldHealthOrganization/app/issues/1824

2020-12-13 23:07 UTC, brunobowden commented on client/lib/pages/onboarding/country_list_page.dart
> +              var listItem = element.name
Use `nameMatch` as that better indicates the purpose. Using `listItem` suggests a pointer to an object not a boolean.
```suggestion
              var nameMatch = element.name
```

2020-12-13 23:07 UTC, brunobowden commented on client/lib/pages/onboarding/country_list_page.dart
> +              return false;
Replace 5 lines with 2:
```suggestion
              return nameMatch ||
                  selectedCountryCode == element.alpha2Code;
```

2020-12-13 23:07 UTC, brunobowden commented
@theswerd - this is basically look good to me but please check this over too

2020-12-13 23:11 UTC, brunobowden commented
@Henrymarks1 - just to clarify my comment. Hard code Nigeria at the top of the list and then every other country below it. As soon as someone types something, then drop Nigeria and go to the filtered list as you're doing in this PR. This is just meant to be a temporary hack until we work out a better solution for multiple countries.

2020-12-14 01:49 UTC, Henrymarks1 commented
@brunobowden Noted! Will have the changes in soon.

2020-12-14 04:02 UTC, brunobowden commented
@Henrymarks1 - thanks for the help. There's two places that the country selection appears, so please update both:
1. Onboarding screen, which I think you've covered
1. Settings page where someone can select their country

2020-12-14 04:30 UTC, brunobowden commented
@Henrymarks1 - unless it's straight forward to update the Settings page too, let's focus on landing this ASAP as we're planning to launch soon.

2020-12-16 06:09 UTC, brunobowden commented
@Henrymarks1 - you should get this update soon if you'd like it to be part of the initial launch. I think it's a welcome improvement, so please update it.

2020-12-16 06:56 UTC, theswerd requested changes
Mostly looks good - see comments

2020-12-16 06:56 UTC, theswerd commented on client/lib/components/page_scaffold/page_header.dart
> +                  ),
Delete unnecessary container

```suggestion
                : headerWidget,
```

2020-12-16 06:56 UTC, theswerd commented on client/lib/components/page_scaffold/page_header.dart
> +          padding: EdgeInsets.symmetric(horizontal: 8, vertical: 2),
Revert change
```suggestion
          padding: EdgeInsets.symmetric(horizontal: 8),
```

2020-12-16 06:56 UTC, theswerd commented on client/lib/pages/onboarding/country_list_page.dart
> +  var listData;
- Define type when giving value late for IDE Intellisense
- Use semantic name
```suggestion
  Iterable<IsoCountry> selectedCountries;
```

2020-12-16 06:56 UTC, theswerd commented on client/lib/pages/onboarding/country_list_page.dart
> +              listData = filtered;
```suggestion
              selectedCountries = filtered;
```

2020-12-16 06:56 UTC, theswerd commented on client/lib/pages/onboarding/country_list_page.dart
> +      body: _buildCountries(listData),
Revert change because selectedCountries is within scope
```suggestion
      body: _buildCountries(),
```

2020-12-16 06:56 UTC, theswerd commented on client/lib/pages/onboarding/country_list_page.dart
> +  List<Widget> _buildCountries(listData) {
Revert change because selectedCountries is within scope
```suggestion
  List<Widget> _buildCountries() {
```

2020-12-16 06:56 UTC, theswerd commented on client/lib/components/page_scaffold/page_header.dart
>    final String title;
```suggestion
  ///Overrides headerWidget parameter
  final String title;
```

2020-12-16 07:20 UTC, brunobowden commented
@Henrymarks1 - we were about to tag a new build tonight and we'd like to include your change. Can you address the remaining items and then mark them resolved in the GitHub conversation. That includes my earlier comment about `return nameMatch || selectedCountryCode == element.alpha2Code;` to reduce the complexity.

2020-12-16 08:10 UTC, theswerd approved these changes
LGTM

2020-12-16 08:10 UTC, brunobowden approved these changes

2020-12-16 08:17 UTC, merged