docs: updated README based on my getting-started experience.
WorldHealthOrganization/app pull request #1960
Opened 2021-03-11 06:15 UTC by rjhuijsman

Updated README with information that would have helped me get started.
Updated Gradle version because Android Studio was adamant that that was a good idea.
Added myself to the credits, as per contributor guidelines.

## Screenshots
None

## How did you test the change?

- [ ] iOS Simulator
- [ ] iOS Device
- [X] Android Simulator
- [ ] Android Device
- [ ] `curl` to a dev App Engine server
- [ ] other, please describe

## Checklist:

- [X] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md) and verified that all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE).

2021-03-11 06:56 UTC, theswerd requested changes
Please remove changes to `client/android/build.gradle` and `client/android/gradle/wrapper/gradle-wrapper.properties`

2021-03-11 06:57 UTC, theswerd commented on client/android/build.gradle
> +        classpath 'com.android.tools.build:gradle:4.1.2'
```suggestion
        classpath 'com.android.tools.build:gradle:3.5.0'
```

2021-03-11 06:57 UTC, theswerd commented on client/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
```suggestion
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
```

2021-03-11 06:58 UTC, theswerd commented on client/android/gradle/wrapper/gradle-wrapper.properties
> +#Tue Mar 09 22:46:39 PST 2021
```suggestion
#Fri Jun 23 08:50:38 CEST 2017
```

2021-03-12 17:14 UTC, rjhuijsman commented
> Please remove changes to `client/android/build.gradle` and `client/android/gradle/wrapper/gradle-wrapper.properties`

Done! Mind teaching a man to fish by explaining why you think it's better left as-is?

2021-03-12 17:15 UTC, theswerd requested changes

2021-03-12 17:15 UTC, theswerd commented on client/README.md
> +flutter run --flavor prod
For development purposes, users should use the staging version in order to allow us access to the server's debug logs.
```suggestion
flutter run --flavor stag
```

2021-03-14 03:47 UTC, theswerd approved these changes
LGTM

2021-03-14 05:28 UTC, rjhuijsman commented
Thanks @theswerd !

I don't have the button to actually do the merge - who should I poke?

2021-03-14 05:29 UTC, theswerd commented
@rjhuijsman Sorry about that - I can merge

2021-03-14 05:29 UTC, merged